"""Generate the static control panel into docs/, for GitHub Pages.

A static page on purpose.  This project is meant to run for ten years, and a
web service that needs maintaining will not survive that -- worse, a dashboard
that dies takes the operator's only view down with it.  A page regenerated by
the same daily job has nothing to keep alive.

No template engine, no CSS framework, no JavaScript: stdlib string building
and inline styles, so the file still renders in a decade.

Two outputs:
    docs/index.html   what a person looks at
    docs/status.json  what a machine reads (and the first step towards the
                      data being citable rather than merely visible)
"""
import argparse
import html
import json
import sys
from datetime import date as _date, datetime, timedelta, timezone

from .db import ROOT, connect

DOCS = ROOT / "docs"
STALE_HOURS = 25

CSS = """
:root{--bg:#fbfaf9;--fg:#1a1a1a;--dim:#6b6b6b;--line:#e5e2de;--card:#fff;
--ok:#15803d;--okbg:#dcfce7;--warn:#a16207;--warnbg:#fef9c3;
--bad:#b91c1c;--badbg:#fee2e2;--none:#e5e2de;--accent:#1d4ed8}
@media (prefers-color-scheme:dark){:root{--bg:#161514;--fg:#ececec;--dim:#9a9a9a;
--line:#2e2c2a;--card:#1e1d1b;--ok:#4ade80;--okbg:#14331f;--warn:#fbbf24;
--warnbg:#3a2e0b;--bad:#f87171;--badbg:#3d1616;--none:#2e2c2a;--accent:#7aa2f7}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",
"Hiragino Sans GB","Microsoft YaHei",sans-serif}
.wrap{max-width:960px;margin:0 auto;padding:28px 18px 64px}
h1{font-size:22px;margin:0 0 2px;letter-spacing:-.01em}
h2{font-size:15px;margin:34px 0 10px;color:var(--dim);font-weight:600;
text-transform:uppercase;letter-spacing:.06em}
.sub{color:var(--dim);font-size:13px;margin-bottom:22px}
.banner{padding:16px 18px;border-radius:10px;border:1px solid var(--line);
margin-bottom:8px;background:var(--card)}
.banner.ok{background:var(--okbg);border-color:transparent}
.banner.warn{background:var(--warnbg);border-color:transparent}
.banner.bad{background:var(--badbg);border-color:transparent}
.banner .big{font-size:19px;font-weight:650}
.banner .why{font-size:13px;color:var(--dim);margin-top:4px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:13px 15px}
.card .n{font-size:22px;font-weight:650;letter-spacing:-.02em}
.card .l{font-size:12px;color:var(--dim);margin-top:2px}
.cal{display:flex;flex-wrap:wrap;gap:3px;margin:6px 0 8px}
.d{width:15px;height:15px;border-radius:3px;background:var(--none)}
.d.ok{background:var(--ok)}.d.warn{background:var(--warn)}.d.bad{background:var(--bad)}
.legend{font-size:12px;color:var(--dim);display:flex;gap:14px;flex-wrap:wrap}
.legend span{display:inline-flex;align-items:center;gap:5px}
.legend i{width:10px;height:10px;border-radius:2px;display:inline-block}
.tw{overflow-x:auto;-webkit-overflow-scrolling:touch}
table{border-collapse:collapse;width:100%;font-size:13px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);
white-space:nowrap;vertical-align:top}
th{color:var(--dim);font-weight:600;font-size:12px}
td.wrapok{white-space:normal;min-width:180px}
code{font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--dim);
word-break:break-all}
a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}
.pill{display:inline-block;padding:1px 7px;border-radius:99px;font-size:11px;font-weight:650}
.pill.high{background:var(--badbg);color:var(--bad)}
.pill.medium{background:var(--warnbg);color:var(--warn)}
.pill.low{background:var(--none);color:var(--dim)}
.bar{height:7px;border-radius:99px;background:var(--none);overflow:hidden;margin-top:6px}
.bar>i{display:block;height:100%;background:var(--bad)}
.foot{margin-top:44px;padding-top:16px;border-top:1px solid var(--line);
font-size:12px;color:var(--dim)}
.en{color:var(--dim);font-weight:400}
.banner .en{font-size:13px;margin-top:3px;line-height:1.45}
h2 .en{font-size:11px;letter-spacing:.04em;margin-left:6px}
.card .l .en{display:block;font-size:11px}
.empty{color:var(--dim);font-size:13px;padding:10px 0}
"""


def _rows(con, sql, params=()):
    return con.execute(sql, params).fetchall()


def _hours_since(ts):
    if not ts:
        return None
    when = datetime.fromisoformat(ts.replace("Z", "+00:00"))
    return (datetime.now(timezone.utc) - when).total_seconds() / 3600


def gather(con):
    """Everything the page and status.json need, computed once."""
    d = {}
    d["generated_at"] = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    d["last_success"] = con.execute(
        "SELECT MAX(finished_at) FROM runs WHERE status IN ('success','partial')"
    ).fetchone()[0]
    age = _hours_since(d["last_success"])
    d["hours_since_success"] = None if age is None else round(age, 1)
    d["stale"] = age is None or age >= STALE_HOURS

    d["observations"] = con.execute("SELECT count(*) FROM observations").fetchone()[0]
    d["entities"] = con.execute("SELECT count(*) FROM entities").fetchone()[0]
    d["days"] = [r[0] for r in con.execute(
        "SELECT DISTINCT observed_date FROM observations ORDER BY observed_date")]
    d["first_day"] = d["days"][0] if d["days"] else None

    # Per-day state, worst run of the day wins.
    per_day = {}
    for r in _rows(con, "SELECT substr(started_at,1,10) d, status FROM runs"):
        rank = {"success": 0, "partial": 1, "failed": 2, "running": 1}.get(r["status"], 1)
        cur = per_day.get(r["d"])
        if cur is None or rank > cur[0]:
            per_day[r["d"]] = (rank, r["status"])
    d["day_status"] = {k: v[1] for k, v in per_day.items()}

    # Calendar from the origin to today; a day with no run at all is a hole,
    # and a hole is the one thing this project exists to prevent.
    d["calendar"] = []
    if d["first_day"]:
        start = _date.fromisoformat(d["first_day"])
        today = datetime.now(timezone.utc).date()
        cur = start
        while cur <= today:
            k = cur.isoformat()
            d["calendar"].append({"date": k, "status": d["day_status"].get(k, "missing")})
            cur += timedelta(days=1)
    d["days_covered"] = sum(1 for c in d["calendar"] if c["status"] != "missing")
    d["days_missing"] = sum(1 for c in d["calendar"] if c["status"] == "missing")

    d["runs"] = [dict(r) for r in _rows(
        con, "SELECT * FROM runs ORDER BY id DESC LIMIT 12")]

    d["changes_by_severity"] = dict(_rows(
        con, "SELECT severity, count(*) FROM changes GROUP BY severity"))
    d["notable"] = [dict(r) for r in _rows(
        con,
        "SELECT c.detected_date, c.severity, c.field, c.old_value, c.new_value,"
        " e.external_id FROM changes c JOIN entities e ON e.id=c.entity_id"
        " WHERE c.severity IN ('high','medium')"
        " ORDER BY c.detected_date DESC, c.severity, c.id DESC LIMIT 40")]

    latest = ("observed_at=(SELECT MAX(observed_at) FROM observations x"
              " WHERE x.entity_id=o.entity_id)")
    one = lambda sql: con.execute(sql).fetchone()[0]
    d["declared"] = one(f"SELECT count(*) FROM observations o WHERE {latest}"
                        " AND declared_license IS NOT NULL")
    d["has_file"] = one(f"SELECT count(*) FROM observations o WHERE {latest}"
                        " AND has_license_file=1")
    d["gap"] = one(f"SELECT count(*) FROM observations o WHERE {latest}"
                   " AND declared_license IS NOT NULL AND has_license_file=0")
    d["undeclared"] = one(f"SELECT count(*) FROM observations o WHERE {latest}"
                          " AND declared_license IS NULL")
    d["gated"] = one(f"SELECT count(*) FROM observations o WHERE {latest} AND is_gated=1")
    d["licenses"] = [dict(r) for r in _rows(con, f"""
        SELECT declared_license lic, count(*) total,
               SUM(CASE WHEN has_license_file=0 THEN 1 ELSE 0 END) nofile
        FROM observations o WHERE {latest} AND declared_license IS NOT NULL
        GROUP BY lic ORDER BY total DESC LIMIT 10""")]

    d["archives"] = [dict(r) for r in _rows(
        con, "SELECT substr(started_at,1,10) d, archive_path, archive_sha256, merkle_root"
             " FROM runs WHERE archive_path IS NOT NULL ORDER BY id DESC LIMIT 10")]
    return d


E = html.escape


def render(d, repo=None):
    P = []
    a = P.append
    a("<!-- generated by src/site.py; do not edit by hand -->")
    a('<meta charset="utf-8">')
    a('<meta name="viewport" content="width=device-width,initial-scale=1">')
    a("<title>ModelPass 中控 · Control Panel</title>")
    a(f"<style>{CSS}</style>")
    a('<div class="wrap">')
    a("<h1>ModelPass 中控 <span class=\"en\">Control Panel</span></h1>")
    origin = d["first_day"] or "—"
    a(f'<div class="sub">开源模型元数据的每日观测记录 · 序列起点 {E(origin)} · '
      f'生成于 {E(d["generated_at"])}<br>'
      f'<span class="en">A daily record of open model metadata. Series origin '
      f'{E(origin)}, page generated {E(d["generated_at"])}.</span></div>')

    # --- is it alive -------------------------------------------------------
    if d["stale"]:
        cls = "bad"
        big = '采集已停止 <span class="en">Collection has stopped</span>'
        if d["last_success"]:
            why = (f'最近一次成功采集在 {E(str(d["last_success"]))},'
                   f'{d["hours_since_success"]} 小时前(阈值 {STALE_HOURS} 小时)。'
                   f'断掉的那一天补不回来。')
            en = (f'Last successful collection {E(str(d["last_success"]))}, '
                  f'{d["hours_since_success"]}h ago, past the {STALE_HOURS}h '
                  f'threshold. A day not collected cannot be back-filled.')
        else:
            why = "从未有过成功的采集。"
            en = "No successful collection has ever been recorded."
    elif d["days_missing"]:
        cls = "warn"
        big = '运行中,但序列有缺口 <span class="en">Running, with gaps</span>'
        why = f'自起点以来有 {d["days_missing"]} 天没有任何采集记录。'
        en = (f'{d["days_missing"]} day(s) since the origin have no collection '
              f"at all. Those days are gone for good.")
    else:
        cls = "ok"
        big = '运行正常 <span class="en">Healthy</span>'
        why = (f'最近一次成功采集 {E(str(d["last_success"]))},'
               f'{d["hours_since_success"]} 小时前 · 连续 {d["days_covered"]} 天无缺口')
        en = (f'Last successful collection {E(str(d["last_success"]))}, '
              f'{d["hours_since_success"]}h ago · {d["days_covered"]} consecutive '
              f"days with no gap.")
    a(f'<div class="banner {cls}"><div class="big">{big}</div>'
      f'<div class="why">{why}<div class="en">{en}</div></div></div>')

    # --- numbers -----------------------------------------------------------
    a('<h2>累计</h2><div class="grid">')
    for n, l in [
        (f'{d["observations"]:,}', '观测记录<span class="en">observations</span>'),
        (f'{d["entities"]:,}', '追踪的模型<span class="en">models tracked</span>'),
        (f'{d["days_covered"]}', '覆盖天数<span class="en">days covered</span>'),
        (f'{d["days_missing"]}', '缺失天数<span class="en">days missing</span>'),
        (f'{d["changes_by_severity"].get("high", 0)}',
         'high 级变更<span class="en">high-severity changes</span>'),
        (f'{d["changes_by_severity"].get("medium", 0)}',
         'medium 级变更<span class="en">medium-severity changes</span>'),
    ]:
        a(f'<div class="card"><div class="n">{n}</div><div class="l">{l}</div></div>')
    a("</div>")

    # --- calendar ----------------------------------------------------------
    a('<h2>每日运行 · 一格一天 <span class="en">Daily runs — one cell per day</span></h2>')
    a('<div class="cal">')
    cmap = {"success": "ok", "partial": "warn", "failed": "bad", "running": "warn"}
    for c in d["calendar"]:
        k = cmap.get(c["status"], "")
        a(f'<div class="d {k}" title="{E(c["date"])} {E(c["status"])}"></div>')
    a("</div>")
    a('<div class="legend">'
      '<span><i style="background:var(--ok)"></i>成功 success</span>'
      '<span><i style="background:var(--warn)"></i>部分失败 partial</span>'
      '<span><i style="background:var(--bad)"></i>失败 failed</span>'
      '<span><i style="background:var(--none)"></i>没跑,这一天永久丢失 '
      "&nbsp;·&nbsp; never ran, that day is gone for good</span>"
      "</div>")

    # --- changes -----------------------------------------------------------
    a('<h2>值得看的变更 · high 与 medium <span class="en">Notable changes — high and medium</span></h2>')
    if not d["notable"]:
        a('<div class="empty">还没有。high 级信号(许可证变更、许可证文件消失、'
          "转为 gated、模型消失)本来就稀有,需要时间积累。"
          '<div class="en">Nothing yet. High-severity signals — a licence '
          "rewritten, a licence file deleted, a model gated or withdrawn — are "
          "rare by nature and only accumulate with time.</div></div>")
    else:
        a('<div class="tw"><table><tr><th>日期 date</th><th>级别 severity</th>'
          "<th>模型 model</th><th>字段 field</th><th>变化 before → after</th></tr>")
        for c in d["notable"]:
            mid = E(c["external_id"])
            old = E(str(c["old_value"] or "∅"))[:44]
            new = E(str(c["new_value"] or "∅"))[:44]
            a(f'<tr><td>{E(c["detected_date"])}</td>'
              f'<td><span class="pill {E(c["severity"])}">{E(c["severity"])}</span></td>'
              f'<td class="wrapok"><a href="https://huggingface.co/{mid}" '
              f'rel="noopener">{mid}</a></td>'
              f'<td><code>{E(c["field"])}</code></td>'
              f"<td><code>{old} → {new}</code></td></tr>")
        a("</table></div>")

    # --- cross-section -----------------------------------------------------
    total = d["declared"] + d["undeclared"]
    if total:
        pct = 100 * d["gap"] / d["declared"] if d["declared"] else 0
        a('<h2>声明的许可证 vs 仓库里真有的文件 <span class="en">Declared licence vs. a licence file in the repo</span></h2>')
        a(f'<div class="banner"><div class="big">{d["gap"]} / {d["declared"]} '
          f"个模型声明了许可证,但仓库里没有任何许可证文件"
          f'<span class="en"> declare a licence but ship no licence file</span></div>'
          f'<div class="why">占声明总数的 {pct:.0f}%。model card 上的一行 YAML 随时可以改,'
          f"改了不留痕 —— 除非有人每天记录。另有 {d['undeclared']} 个模型连声明都没有,"
          f'{d["gated"]} 个需要申请才能下载(gated)。'
          f'<div class="en">{pct:.0f}% of everything that declares one. That '
          f"declaration is a line of YAML in a model card: it can be rewritten "
          f"at any time and leaves no trace behind — unless somebody is writing "
          f"it down every day. A further {d['undeclared']} models declare no "
          f"licence at all, and {d['gated']} are gated.</div></div>"
          f'<div class="bar"><i style="width:{pct:.0f}%"></i></div></div>')
        a('<div class="tw"><table><tr><th>许可证 licence</th><th>模型数 models</th>'
          "<th>其中无文件 no file</th><th>比例 share</th></tr>")
        for r in d["licenses"]:
            p = 100 * r["nofile"] / r["total"] if r["total"] else 0
            a(f'<tr><td><code>{E(r["lic"])}</code></td><td>{r["total"]}</td>'
              f'<td>{r["nofile"]}</td><td>{p:.0f}%</td></tr>')
        a("</table></div>")

    # --- runs --------------------------------------------------------------
    a('<h2>最近的运行 <span class="en">Recent runs</span></h2>')
    a('<div class="tw"><table><tr><th>#</th><th>开始 started (UTC)</th>'
      "<th>状态 status</th><th>尝试 attempted</th><th>成功 ok</th>"
      "<th>失败 failed</th></tr>")
    for r in d["runs"]:
        cls = {"success": "low", "partial": "medium", "failed": "high"}.get(r["status"], "low")
        a(f'<tr><td>{r["id"]}</td><td><code>{E(str(r["started_at"]))}</code></td>'
          f'<td><span class="pill {cls}">{E(str(r["status"]))}</span></td>'
          f'<td>{r["attempted"]}</td><td>{r["succeeded"]}</td><td>{r["failed"]}</td></tr>')
    a("</table></div>")

    # --- integrity ---------------------------------------------------------
    a('<h2>归档存证 <span class="en">Archive integrity</span></h2>')
    a('<div class="tw"><table><tr><th>日期 date</th><th>归档 archive</th>'
      "<th>merkle root</th></tr>")
    for r in d["archives"]:
        a(f'<tr><td>{E(str(r["d"]))}</td>'
          f'<td><code>{E(str(r["archive_path"]).split("/")[-1])}</code></td>'
          f'<td><code>{E(str(r["merkle_root"] or ""))}</code></td></tr>')
    a("</table></div>")

    link = f'<a href="{E(repo)}" rel="noopener">{E(repo)}</a>' if repo else "源码仓库"
    a(f'<div class="foot">这一页由每日采集任务生成,没有服务器、没有数据库连接、'
      f"没有需要维护的服务 —— 它只是一个文件。"
      f"观测只增不改;本页与摘要都是派生结果,可随时重算。"
      f"归档以 SHA-256 与 Merkle root 存证。<br>"
      f'<span class="en">Generated by the daily collection job. No server, no '
      f"database connection, nothing to keep alive — it is just a file. "
      f"Observations are append-only; this page and the daily summaries are "
      f"derived and can be recomputed at any time. Archives are pinned by "
      f"SHA-256 and a Merkle root.</span><br>"
      f'{link} · <code>status.json</code> 提供机器可读的同一份数据 '
      f'<span class="en">— the same data, machine-readable.</span></div>')
    a("</div>")
    return "\n".join(P) + "\n"


def build(con, repo=None, verbose=False):
    DOCS.mkdir(parents=True, exist_ok=True)
    d = gather(con)
    (DOCS / "index.html").write_text(render(d, repo), encoding="utf-8")
    machine = {k: v for k, v in d.items() if k not in ("calendar", "notable", "runs")}
    machine["calendar"] = d["calendar"]
    machine["notable_changes"] = d["notable"]
    (DOCS / "status.json").write_text(
        json.dumps(machine, ensure_ascii=False, indent=1, default=str) + "\n",
        encoding="utf-8")
    # Tell GitHub Pages not to run Jekyll over this.
    (DOCS / ".nojekyll").write_text("", encoding="utf-8")
    if verbose:
        print(f"[site] wrote {DOCS/'index.html'} and {DOCS/'status.json'}")
    return d


def main(argv=None):
    ap = argparse.ArgumentParser(prog="python -m src.site")
    ap.add_argument("--db", help="database path")
    ap.add_argument("--repo", default="https://github.com/HOIGO2025/modelpass")
    args = ap.parse_args(argv)
    con = connect(args.db)
    try:
        build(con, args.repo, verbose=True)
    finally:
        con.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
